name = "vakeelsahab"
# Wrangler configuration for Vakeel Sahab GPT
compatibility_date = "2026-05-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "vakeel_db"
database_name = "vakeel-db"
database_id = "6cb67aca-64b3-4bdd-a2b9-0bd1b37fc348"

[[vectorize]]
binding = "VECTORIZE"
index_name = "vakeel-vectors"
